### ISSUE TITLE
File download examples need to be updated

### ISSUE THREAD

**Issue by TaylorKrusen** [hellosign/hellosign-openapi#160]
Revisit all examples for downloading a file. It doesn't make sense to print_r a stream response
![Image from iOS (3)](https://user-images.githubusercontent.com/20376095/203382419-e68d3970-d3ec-4aa0-a0fa-366f7d7f1cf0.jpg)

**Comment by jtreminio-dropbox** [comment]
node: https://github.com/hellosign/hellosign-openapi/pull/172
php: https://github.com/hellosign/hellosign-openapi/pull/168

**Comment by jtreminio-dropbox** [comment]
ruby: https://github.com/hellosign/hellosign-openapi/pull/166

**Comment by jtreminio-dropbox** [comment]
Last one: https://github.com/hellosign/hellosign-openapi/pull/175
