### ISSUE TITLE
Incorrect description for sms signature request delivery

### ISSUE THREAD

**Issue by TaylorKrusen** [hellosign/hellosign-openapi#161]
support for signature request delivery via SMS was added and is currently in beta. However the description for [sms_phone_number_type](https://developers.hellosign.com/api/reference/operation/signatureRequestSend/#!ct=application/json&path=signers/sms_phone_number_type&t=request) is currently incorrect. This feature delivers a link to complete a signature request. It does **not** distribute a completed document.

**Comment by babiweltson** [comment]
Included correct description on https://github.com/hellosign/hellosign-openapi/pull/166
