### ISSUE TITLE
Bug: incorrect error message for file parameter in node SDK

### ISSUE THREAD

**Issue by TaylorKrusen** [hellosign/hellosign-openapi#162]
The Legacy SDK Node SDK passed files with a `files` parameter.
The new, OAS-powered Node SDK passes files with a `file` parameter.

In order to pass a file path (instead of binary), the new Node SDK requires that you set `instantiateFiles` to `true`. 

When `instantiateFiles` is set to `false` (or not set at all), the following behaviors occur: 
**Expected**: Passing a file path using the `file` parameter should return an error about incorrect types. 
**Actual**: The error says the parameter is incorrect.
```
Exception when calling HelloSign API:
_ErrorResponse {
  error: _ErrorResponseError {
    errorMsg: 'Must specify file(s) to be sent.',
    errorName: 'bad_request',
    errorPath: undefined
  }
}
```

**Comment by jtreminio-dropbox** [comment]
`instantiateFiles` is kind of unsafe and really only needed for in unit tests when passing a JSON string / object to the SDKs.

It's a little hard to visualize here on github, but take this PHP example: https://github.com/hellosign/hellosign-openapi/blob/development/examples/SignatureRequestSend.php

This is how I would prefer users use the SDK, _but_ it's also doable by passing this JSON blob: https://github.com/hellosign/hellosign-openapi/blob/development/test_fixtures/SignatureRequestSendRequest.json

Honestly I would much rather get rid of `file` (and any other binary parameter from other endpoints) support in our unit test and instead implement something similar to what we did for the SDK tester: https://github.com/hellosign/sdk-tester/blob/main/test_fixtures/signatureRequestSend-example_01.json

In that example, we've clearly separated out the binary properties from everything else.

**Comment by jtreminio-dropbox** [comment]
Removed.
