### ISSUE TITLE
The search fields for the query when hitting the /signature_request/list through java code.

### ISSUE THREAD

**Issue by rinky2** [hellosign/hellosign-openapi#264]
For the 'query=null', the response is received. But while specifying the search fields, we are having difficulty in getting response. The signature_request returns the empty response i.e. signatureRequests: []. This maybe because we might be specifying wrong string in query. So it will be great if the query string format is specified in sample code. Note: While hitting the API in the documentation we are receiving the desired response but through code as mentioned earlier returns the empty response.

**Comment by jtreminio-dropbox** [comment]
`query` is just a Kibana string, [here is some information on how to use it](https://developers.hellosign.com/api/reference/search/).

**Comment by jtreminio-dropbox** [comment]
Let me know if there's anything else I can help you with!
