### ISSUE TITLE
Java SDK (v1.1.1) - java.lang.NoClassDefFoundError: javax/ws/rs/core/Configuration

### ISSUE THREAD

**Issue by adang-teamim** [hellosign/hellosign-openapi#285]
Hello,

We updated spring and as such needed to update the tomcat container we were hosting our application on. We are running into a NoClassDefFoundError.

When calling `var apiClient = Configuration.getDefaultApiClient();`, we get the following error: `java.lang.NoClassDefFoundError: javax/ws/rs/core/Configuration`

We've tried multiple things in our pom file including:

1. Adding the javax.ws.rs dependency - this results in the error: `java.lang.LinkageError: ClassCastException: attempting to castjar:file:/usr/local/tomcat/webapps/api/WEB-INF/lib/javax.ws.rs-api-2.1.1.jar!/javax/ws/rs/client/ClientBuilder.class to jar:file:/usr/local/tomcat/webapps/api/WEB-INF/lib/javax.ws.rs-api-2.1.1.jar!/javax/ws/rs/client/ClientBuilder.class`
2. Setting the javax.ws.rs dependency scope to "provided" - this gives the NoClassDefFoundError
3. Setting the dropbox-sign dependency scope to "compile" - this gives the NoClassDefFoundError

Here might be some relevant information surrounding the container:

`tomcat/lib# java -cp catalina.jar org.apache.catalina.util.ServerInfo
Server version: Apache Tomcat/10.1.6
Server built:   Feb 19 2023 13:23:52 UTC
Server number:  10.1.6.0
OS Name:        Linux
OS Version:     5.4.0-1103-azure
Architecture:   amd64
JVM Version:    17.0.6+10
JVM Vendor:     Eclipse Adoptium

# java -version
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)`

Here was the [container we were using before](https://hub.docker.com/layers/library/tomcat/8.5.81-jre8-temurin-jammy/images/sha256-451c55bf926251549a80e8e1a8b571a1afaeed6fcf5f7b328397795c0633dce5)

Here is the [updated container](https://hub.docker.com/layers/library/tomcat/10.1.6-jre17-temurin-jammy/images/sha256-7b4c5a067821d97bffe7c45240357f41cd1f913d2ccfbfaab6f870b0f4009dec?context=explore)

Is there anything we may be missing here?

**Comment by adang-teamim** [comment]
@jtreminio-dropbox Tagging you for visiblity

**Comment by adang-teamim** [comment]
@jtreminio-dropbox We've found a tenuous explanation of what we may be running in to, dropbox sign is using OpenAPI Generator (https://github.com/hellosign/dropbox-sign-java#about-this-package) to create the libraries that we're using, it looks like there are special steps needed when using OpenAPI Generator for code that's spring 3 compatible (https://github.com/OpenAPITools/openapi-generator/issues/14143)

Can you confirm if this may be the case?

**Comment by fenghao-chen** [comment]
Hi @adang-teamim, I'll take a look and get back to you.

**Comment by fenghao-chen** [comment]
Hi @adang-teamim, when calling 
```
var apiClient = Configuration.getDefaultApiClient();
```
the `Configuration` is not really referring to `javax.ws.rs.core.Configuration`, in fact it should be `com.dropbox.sign.Configuration`. I'm not entirely sure why it was working for you before the container update though.  Could you add `import com.dropbox.sign.Configuration;` as import (and delete the javax.ws.rs one) and let me if that fixes the issue?

**Comment by adang-teamim** [comment]
Hey @fenghao-chen, here are all the imports we are using. We aren't importing the javax.ws.rs.core.Configuration

`import java.io.File;
import java.time.Instant;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import com.dropbox.sign.ApiException;
import com.dropbox.sign.Configuration;
import com.dropbox.sign.api.*;
import com.dropbox.sign.auth.HttpBasicAuth;
import com.dropbox.sign.model.*;
import com.team.greensign.bean.ClientSignature;
import com.team.greensign.bean.Vars;
import com.team.greensign.util.Authentication;
import com.team.greensign.util.Constants;
import com.team.greensign.util.HttpGetRequest;`

**Comment by adang-teamim** [comment]
@fenghao-chen Would you say the Dropbox Sign Java SDK is compatible with Spring Boot 3.0?

**Comment by fenghao-chen** [comment]
Hi @adang-teamim, your observation is correct. Our Java SDK has dependencies on `javax.*`, which has been renamed to `jakarta.*` after Jakarta EE 9. The team is exploring the idea of removing the dependencies, but as of now the SDK is not compatible with Spring Boot 3.0 or Apache Tomcat 10.  Sorry for the inconvenience!

**Comment by christiangoudreau** [comment]
This is also important for us, we can't upgrade to spring boot 3 because of it... jarkata annotations comes in conflic with javax.

**Comment by christiangoudreau** [comment]
Bumping us, this is really slowing us down

**Comment by jtreminio-dropbox** [comment]
Apologies on this - we're still debating how to best resolve the issue, but at this point it seems like the only choice we (Dropbox Sign) have is to spin up a new Java SDK to support `jakarta`, which is not exactly ideal for us.

**Comment by jtreminio-dropbox** [comment]
We're interested in moving forward. Unfortunately, our engineer that helped work on the Java SDK is no longer with the company. We're slowly figuring out what needs changed, and how to test, to be able to offer a new Java SDK that uses Jakarta.

The plan is to keep two versions of the Java SDK.

**Comment by jtreminio-dropbox** [comment]
Howdy again! Would you be able to provide us with a small app showing the broken dependency? Internal testing within our team shows the `dropbox-sign` Java SDK working fine with a Tomcat 10 app.

**Comment by christiangoudreau** [comment]
In a spring boot 3 project ?

**Comment by jtreminio-dropbox** [comment]
Can folks within this thread test out #321 to see if it addresses their problems?

**Comment by mbukowicz** [comment]
Hey @adang-teamim and @christiangoudreau, I was wondering if you had a chance to test https://github.com/hellosign/hellosign-openapi/pull/321?

**Comment by adang-teamim** [comment]
> Hey @adang-teamim and @christiangoudreau, I was wondering if you had a chance to test #321?

Hi, we are pretty set in our custom implementation and do not have a reason nor time to test this. Sorry

**Comment by christiangoudreau** [comment]
Omg I missed this! 

I'm going to try it right now !

**Comment by jtreminio-dropbox** [comment]
[dropbox-sign.jar.zip](https://github.com/hellosign/hellosign-openapi/files/13518952/dropbox-sign.jar.zip)

@christiangoudreau here's the compiled package to test it out.

**Comment by autumnfound** [comment]
> [dropbox-sign.jar.zip](https://github.com/hellosign/hellosign-openapi/files/13518952/dropbox-sign.jar.zip)
> 
> @christiangoudreau here's the compiled package to test it out.

Hey! I looked into this as we also need the Jakarta upgrade jar, and had some mixed results. While the artifacts compiled properly, we had some unexpected failures when attempting to test creating requests with a template locally. I've included below the raw request body sent by the above jar (1), and the message returned by the API (2). I've scrubbed out some of the personal data, but it had more realistic data in there previously. 

I'll also include below the raw request body posted by the 1.1.0 jar which is the current version we use (3) which succeeded in creating a Hellosign document request. The difference I see is that the `metadata` property has an empty default value in the new Jar, where before it was ignored when unset. When I pull our current code and add an empty map to the `metadata` property, I see the same error. I'll include our current method of calling the endpoint as well for reference (4).

1
```json
{
    "template_ids": [
        "****"
    ],
    "signers": [
        {
            "role": "client",
            "name": "****",
            "email_address": "test@eclipse-foundation.org"
        },
        {
            "role": "validator",
            "name": "ECLIPSE EMO-RECORDS",
            "email_address": "test@eclipse-foundation.org"
        },
        {
            "role": "signing_authority",
            "name": "****",
            "email_address": "test@eclipse-foundation.org"
        }
    ],
    "allow_decline": false,
    "is_qualified_signature": false,
    "is_eid": false,
    "message": "You're signature has been requested for the following document by the Eclipse Foundation. ",
    "metadata": {},
    "subject": "Action Required - Eclipse Foundation Signature Request",
    "test_mode": true,
    "title": "Eclipse Foundation Individual Committer Agreement - TEST"
}
```

2
```text
com.dropbox.sign.ApiException: class ErrorResponse {
    error: class ErrorResponseError {
        errorMsg: Metadata is malformed
        errorName: bad_request
        errorPath: null
    }
}
```

3
```json
{
    "template_ids": [
        "****"
    ],
    "signers": [
        {
            "role": "client",
            "name": "****",
            "email_address": "sample@eclipse-foundation.org"
        },
        {
            "role": "validator",
            "name": "ECLIPSE EMO-RECORDS",
            "email_address": "sample@eclipse-foundation.org"
        },
        {
            "role": "signing_authority",
            "name": "****",
            "email_address": "sample@eclipse-foundation.org"
        }
    ],
    "allow_decline": false,
    "is_qualified_signature": false,
    "message": "You're signature has been requested for the following document by the Eclipse Foundation. ",
    "subject": "Action Required - Eclipse Foundation Signature Request",
    "test_mode": true,
    "title": "Eclipse Foundation Individual Committer Agreement - TEST"
}
```

4
Where `template` is a custom config object that represents a Hellosign template, `request` is the request body we consume to generate the request, and `signers` is a list of processed user objects that was initially included in the request. 
```java
            SignatureRequestGetResponse r = signatureRequest
                    .signatureRequestSendWithTemplate(new SignatureRequestSendWithTemplateRequest()
                            .templateIds(List.of(template.templateId()))
                            .title(template.templateName() + (config.testMode() ? " - TEST" : ""))
                            .subject(request.getSubject())
                            .message(request.getMessage())
                            .signers(signers
                                    .stream()
                                    .map(signer -> new SubSignatureRequestTemplateSigner()
                                            .role(signer.getRole())
                                            .emailAddress(signer.getMail())
                                            .name(signer.getName()))
                                    .collect(Collectors.toList()))
                            .testMode(config.testMode()));
```

**Comment by autumnfound** [comment]
@jtreminio-dropbox I was able to successfully post with that update! That's our main use case covered, as our usage of the API is still pretty light as this is an early iteration

**Comment by jtreminio-dropbox** [comment]
We seem to have enough interest in a jakarta version of our Java SDK that it makes sense to officially support it.

The plan right now is to create a `2.x` version of the Java SDK that uses jakarta, while the `1.x` version will continue using javax.

I will post updates to this thread with progress.

**Comment by jtreminio-dropbox** [comment]
We've officially released the new Java SDK with jakarta support! The package name remains the same!

* Version `1.x` will remain using javax. It is now on `1.4.0`
* Version `2.x` will now use jakarta. It is now on `2.0.0`
