### ISSUE TITLE
Ruby SDK (v1.1.1) extra slash added to base path

### ISSUE THREAD

**Issue by lworkman** [hellosign/hellosign-openapi#289]
`DropBox::Sign::Configuration` adds an extra slash between the host and the base path when calling `base_url`. This causes all requests sent through the SDK to use a misspelled URL.

For instance:
```
Dropbox::Sign::EmbeddedApi.new.api_client.config.base_url
=> "https://api.hellosign.com//v3"
```

I'm in the middle of migrating and noticed this. We override the URL so we can run a mock server for some simple testing and the new SDK wasn't hitting it properly.

**Comment by lworkman** [comment]
Thanks for the quick turn around @jtreminio-dropbox!

**Comment by jtreminio-dropbox** [comment]
@lworkman v1.1.2 has been released: https://rubygems.org/gems/dropbox-sign
