### ISSUE TITLE
HelloSign python SDK generated with the openapi-sdk.yaml is different from the SDK project provided in this repo

### ISSUE THREAD

**Issue by MeikandaNayanar** [hellosign/hellosign-openapi#298]
I am trying to generate the python SDK of the hellosign with this yaml [https://github.com/hellosign/hellosign-openapi/blob/main/openapi-sdk.yaml][1]

The below is the command I am using to generate the SDK

>java -jar openapi-generator-cli-6.6.0.jar generate -i D:\openapi-sdk.yaml -g python -o c:\temp\hellosign_python --skip-validate-spec --additional-properties packageName=hellosign.sdk

But the SDK project generated is different from the once they have generated here https://github.com/hellosign/hellosign-openapi/tree/main/sdks/python. 

Few API classes are not there. __init__.py is different with separate clients and so on. How to generate the SDK project same as they have generated?

  [1]: https://github.com/hellosign/hellosign-openapi/blob/main/openapi-sdk.yaml

**Comment by jtreminio-dropbox** [comment]
To generate a specific SDK run `./generate-sdks -t {lang}` - yours would be `./generate-sdks -t python`.
