### ISSUE TITLE
error when using by JavaScript 

### ISSUE THREAD

**Issue by zwh0711** [hellosign/hellosign-openapi#302]
I want to try @dropbox/sign in my vue project. When I install @dropbox/sign with npm and import it in my vue component, it has some mistake.
My operation is like this：
1. npm install @dropbox/sign
2. import * as DropboxSign from "@dropbox/sign";

This is the error I encountered：
 These relative modules were not found:
  * ./aes in ./node_modules/@dropbox/sign/dist/api.js
  * ./cipher-core in ./node_modules/@dropbox/sign/dist/api.js
  * ./core in ./node_modules/@dropbox/sign/dist/api.js
  * ./enc-base64 in ./node_modules/@dropbox/sign/dist/api.js
  * ./enc-base64url in ./node_modules/@dropbox/sign/dist/api.js
  * ./enc-utf16 in ./node_modules/@dropbox/sign/dist/api.js
  * ./evpkdf in ./node_modules/@dropbox/sign/dist/api.js
  * ./format-hex in ./node_modules/@dropbox/sign/dist/api.js
  * ./hmac in ./node_modules/@dropbox/sign/dist/api.js
  * ./lib-typedarrays in ./node_modules/@dropbox/sign/dist/api.js
  * ./md5 in ./node_modules/@dropbox/sign/dist/api.js
  * ./mode-cfb in ./node_modules/@dropbox/sign/dist/api.js
  * ./mode-ctr in ./node_modules/@dropbox/sign/dist/api.js
  * ./mode-ctr-gladman in ./node_modules/@dropbox/sign/dist/api.js
  * ./mode-ecb in ./node_modules/@dropbox/sign/dist/api.js
  * ./mode-ofb in ./node_modules/@dropbox/sign/dist/api.js
  * ./pad-ansix923 in ./node_modules/@dropbox/sign/dist/api.js
  * ./pad-iso10126 in ./node_modules/@dropbox/sign/dist/api.js
  * ./pad-iso97971 in ./node_modules/@dropbox/sign/dist/api.js
  * ./pad-nopadding in ./node_modules/@dropbox/sign/dist/api.js
  * ./pad-zeropadding in ./node_modules/@dropbox/sign/dist/api.js
  * ./pbkdf2 in ./node_modules/@dropbox/sign/dist/api.js
  * ./rabbit in ./node_modules/@dropbox/sign/dist/api.js
  * ./rabbit-legacy in ./node_modules/@dropbox/sign/dist/api.js
  * ./rc4 in ./node_modules/@dropbox/sign/dist/api.js
  * ./ripemd160 in ./node_modules/@dropbox/sign/dist/api.js
  * ./sha1 in ./node_modules/@dropbox/sign/dist/api.js
  * ./sha224 in ./node_modules/@dropbox/sign/dist/api.js
  * ./sha256 in ./node_modules/@dropbox/sign/dist/api.js
  * ./sha3 in ./node_modules/@dropbox/sign/dist/api.js
  * ./sha384 in ./node_modules/@dropbox/sign/dist/api.js
  * ./sha512 in ./node_modules/@dropbox/sign/dist/api.js
  * ./tripledes in ./node_modules/@dropbox/sign/dist/api.js
  * ./x64-core in ./node_modules/@dropbox/sign/dist/api.js
 
How should I test it locally？Do I need to install some other packages?

**Comment by jtreminio-dropbox** [comment]
Howdy! I see you mentioned Vue - the `@dropbox/sign` library is a node package. Can you confirm?
