### ISSUE TITLE
Vulnerability in axios (CSRF)

### ISSUE THREAD

**Issue by dt-hugues-lerebours** [hellosign/hellosign-openapi#328]
Could you please upgrade `axios` dependency to 1.6.0, following vulnerability found in previous versions?
Snyk's report: https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459
Thanks!

**Comment by jtreminio-dropbox** [comment]
We'll need to do some research around this. Unfortunately the openapi-generator template for the `typescript-node` client uses a fairly old axios version, `^0.24.0`. We'll need to verify that the newest axios is backwards-compatible with what we're using.

**Comment by jtreminio-dropbox** [comment]
[Version 1.2.2](https://www.npmjs.com/package/@dropbox/sign/v/1.2.2) published
