### ISSUE TITLE
Make fontSize truly optional

### ISSUE THREAD

**Issue by ArtemDintecom** [hellosign/hellosign-openapi#332]
The .NET SDK version 1.2.0 added a new field `fontSize`, which has an `int` type and a default value of `0`.
Code that previously worked now crashes with the error `'font_size' must be between 7 and 49`.
I think the type should be `int?`, not `int` and the default value is `null`.

I haven't dug deep, but it looks like this problem exists in other SDKs, such as Java.

By the way, what was the default value in past versions of the SDK so that I could make a quick fix?

**Comment by jtreminio-dropbox** [comment]
What endpoint did you call where you saw `font_size` not being returned? This would help us track down any errant bug on our backend.

`font_size` was recently added to the OAS, see #303

**Comment by ArtemDintecom** [comment]
Sorry, I forgot to mention a specific API. This is Send Signature Request `https://api.hellosign.com/v3/signature_request/send`. Now I have to fill in the `font_size` field in the `form_fields_per_document` array in `SubFormFieldsPerDocumentText` and `SubFormFieldsPerDocumentDateSigned` (maybe there are others that I don't use), otherwise 0 will be sent, which is not valid.

**Comment by jtreminio-dropbox** [comment]
Thank you for the information, it clears up the problem.

The change was made to the internal API backend. We can fix this but our release schedule will not roll out the fix until next week Wednesday, after the holidays.

**Comment by jtreminio-dropbox** [comment]
Closing this as the issue was resolved.
