### ISSUE TITLE
Node.js SDK - Hanging Promises in SDK Due to Missing Error Handling in Various Endpoints

### ISSUE THREAD

**Issue by adrianmxb** [hellosign/hellosign-openapi#338]
Hi,

just noticed while working on an error regarding the cancellation of signatures, that the error handling in the SDK is missing for certain endpoints, leading to hanging/stuck promises.

https://github.com/hellosign/dropbox-sign-node/blob/723299047cd3785d8793c3234e7f3357e0934312/api/signatureRequestApi.ts#L553-L581

```ts
    return interceptorPromise.then(() => {
      return new Promise<returnTypeI>((resolve, reject) => {
        axios.request(localVarRequestOptions).then(
          (response) => {
            let body = response.data;


            if (
              response.status &&
              response.status >= 200 &&
              response.status <= 299
            ) {
              resolve({ response: response, body: body });
            } else {
              reject(new HttpError(response, body, response.status));
            }
          },
          (error: AxiosError) => {
            if (error.response == null) {
              reject(error);
              return;
            }


            const response = error.response;


            let body;
          }
        );
      });
    });
```
This is just one example, there are multiple cases like this throughout the SDK.

As you can see, the `reject` is never called, the error handler is basically empty.
I played around a bit and noticed, that this is caused by running `prettier`. I tried updating `prettier` to the latest version, but the error persists. Since its autogenerated code, I think disabling it should be a quick fix, but I also saw that you do some post processing afterwards, not sure if that would break when disabling `prettier`.

**Comment by jtreminio-dropbox** [comment]
Thanks for this report. It's a bit embarrassing we missed this, and that's unexpected (by me) behavior from Prettier.

We'll try to get a fix out today.

**Comment by jtreminio-dropbox** [comment]
@adrianmxb [@dropbox/sign 1.2.3](https://www.npmjs.com/package/@dropbox/sign) has been released with this fix. Thanks again for the report.

**Comment by adrianmxb** [comment]
Thanks, Juan! 🎉
