### ISSUE TITLE
Question: Is it possible to test new Embedded Requesting and Embedded Templates flows using the SDKs?

### ISSUE THREAD

**Issue by LLCampos** [hellosign/hellosign-openapi#350]
Context: https://faq.hellosign.com/hc/en-us/articles/19742714512013-How-to-test-upcoming-features-with-the-Dropbox-Sign-API

And:

<img width="540" alt="image" src="https://github.com/hellosign/hellosign-openapi/assets/12008784/69414571-0747-4d4f-a8af-c28274bfa424">

**Comment by collinWheeler** [comment]
Testing the new Embedded UI will require a regular (non-SDK) request being sent to the endpoint discussed in the "How to test upcoming features with the feature endpoint method" section of that FAQ. Once activated, the Embedded UI will load the new updates.
