### ISSUE TITLE
Dotnet SDK: Method not found error when using RestSharp v109.0.0+ and Dropbox.Sign v1.4.0

### ISSUE THREAD

**Issue by shuyck** [hellosign/hellosign-openapi#369]
Recent change to the RestSharp nuget package causes the following error:

`Method not found: 'RestSharp.RestRequest RestSharp.RestRequestExtensions.AddFile(RestSharp.RestRequest, System.String, Byte[], System.String, System.String)'`

Steps to replicate:
1. Install nuget Dropbox.Sign(1.4.0)
2. Install newst RestSharp v109.0.0+
3. Use one of the code examples we provide in our repo
4. See exception

The minor [change](https://github.com/restsharp/RestSharp/pull/1986/files) in RestSharp was to the `filename` parameter in the `AddFile()` method (`filename` -> `fileName`). Possible breaking change because a named argument is being changed.

**Comment by jtreminio-dropbox** [comment]
RestShartp updated to 110.2.0 in #405

**Comment by luisjones** [comment]
Hi @jtreminio-dropbox is there a timeframe as to when this will be released? the latest version on nuget is 1.5.0 & still an issue for us as we have internal dependencies using a later version of Restsharp. Thanks

**Comment by jtreminio-dropbox** [comment]
Howdy! [Dropbox.Sign 1.6.0](https://www.nuget.org/packages/Dropbox.Sign) was released with [RestSharp 112.0.0](https://github.com/hellosign/dropbox-sign-dotnet/blob/1.6.0/src/Dropbox.Sign/Dropbox.Sign.csproj#L27)
